server:
  port: 9988
  servlet:    context-path: /strategy
  
northstar:
  message.endpoint: http://localhost:51888
  server.endpoint: http://localhost:8888/trader
  
spring:
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: DB_BAR_DATA
logging:
  level: 
    root: info
  path: log/NorthstarStrategyClient/
  
  
strategy-setting:
  demo-strategy:
    gatewayId: Simnow724
    accountId: 094020@Simnow724
    strategyName: DemoStrategy
    mdtdContracts: AP000@AP010,CF000@CF009
    tickRefLen: 5
    barRefLen: 1024
    
  shadow-strategy:
    gatewayId: Simnow724
    accountId: CTP-SimNow
    strategyName: ShadowStrategy
    tradeContracts: AP000@AP010,CF000@CF009
    followAccount: CTP-SimNow
    
    